# Generated by Django 4.2.3 on 2023-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kryptopigula', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
            ],
        ),
    ]
